### ISSUE TITLE
update.py执行错误

### ISSUE THREAD

**Issue by HuanMeng0** [open-power-workgroup/Hospital#220]
python update.py执行错误：
```
Traceback (most recent call last):
  File "update.py", line 13, in <module>
    from resource.python_resource import json_writer
ImportError: No module named python_resource
```

**Comment by chantisnake** [comment]
不能重现，你用的是 python 3 还是 2？

**Comment by xokctah** [comment]
@chantisnake 其实我也有这个问题，Python2.7，尝试了“pip install resource”，仍然同样问题。

**Comment by chantisnake** [comment]
这个需要用 python 3 跑，我可以这两天试试兼容 python 2。

**Comment by xokctah** [comment]
看大家需求，我个人倒是用Python 3也可以。

**Comment by HuanMeng0** [comment]
THX
希望尽快兼容py2.6.x

**Comment by chantisnake** [comment]
py2.6 多半没戏了。。。我会尽力兼容 anaconda 2 （其实并没有太大区别）

**Comment by HuanMeng0** [comment]
QAQ

**Comment by chantisnake** [comment]
毕竟现在 python 最新版已经更新到 python 2.7.11 了。。。（而且不是说 python 2 不会有大更新了么）

**Comment by HuanMeng0** [comment]
@chantisnake 
现在我换成了py3，一样报错……
python3 update.py:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 13, in <module>
    from resource.python_resource import json_writer
ImportError: No module named 'resource.python_resource'; 'resource' is not a package
```

**Comment by chantisnake** [comment]
我看一看，会尽快修复

**Comment by chantisnake** [comment]
![capture](https://cloud.githubusercontent.com/assets/10100995/15092771/6d169068-1441-11e6-8c00-5d2c8a19ec86.PNG)
对不起，实在不能重现，我用的是 python 3.5.1 。。。

**Comment by HuanMeng0** [comment]
@chantisnake 
Py版本是3.4.4

**Comment by chantisnake** [comment]
因为现在还有其他 bug 要修复，文档要写，我可能要过几天才能搞这个了。

对不起

**Comment by HuanMeng0** [comment]
那我试试py351 version

**Comment by HuanMeng0** [comment]
换了351依旧一样
能否告知下你的测试服务器的环境？
@chantisnake

**Comment by HuanMeng0** [comment]
等等，请问你在Linux(CentOS)上测试过吗？
@chantisnake

**Comment by chantisnake** [comment]
windows 10，并没在 linux 上测试过，你可以修改写 pr

**Comment by HuanMeng0** [comment]
遇到了点问题：
```
[root@localhost Hospital]# python3 update.py
run in normal mode
we encounter a warning will parsing readme:
this line is a duplicate info of previous info
Traceback (most recent call last):
  File "update.py", line 37, in <module>
    run()
  File "update.py", line 21, in run
    info_dict = readme_reader.read()
  File "/home/AutoGithub/Hospital/resource/python_resource/readme_reader.py", line 196, in read
    info_dict = __parse_all__(lines[start:end])
  File "/home/AutoGithub/Hospital/resource/python_resource/readme_reader.py", line 150, in __parse_all__
    print('"' + content_line[:-1] + '"')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)
```

**Comment by chantisnake** [comment]
这是因为不能在 console 中输出 unicode，这个可以修

**Comment by chantisnake** [comment]
但是在 ide 中测试没问题

**Comment by HuanMeng0** [comment]
已修好。
做点记录，迟点(或不会)提交PR

```
import io
import sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')
```
to update.py

https://segmentfault.com/q/1010000004433529


```
touch resource/__init__.py
touch resource/python_resource/__init__.py
```
to resource/* path


PythonVersion:3.5.1
SystemVersion:CentOS6.7(Final)

**Comment by chantisnake** [comment]
好的，我会提交 pr，谢谢了！

**Comment by HuanMeng0** [comment]
QwQ
